output_dir = 'steps'
src_dir = 'BookThing'
chapter_prefix = 'step'
skip_dirs = ['htmlcov']
skip_patterns = [
    '__pycache__', '.swp', 'db.sqlite3', 'runtests.sh', 'req_dev.txt',
    'pyflakes.sh',
]
pound_globs = ['**/*.py', '**/requirements.txt' ]
delete_output = true
black = true
isort = true

#[ranged_files.99_final]
#range = '45-'
#files = [
#    'RiffMates/tests/',
#]
