# Generated by Django 5.0.6 on 2024-07-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("libthing_id", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
            ],
        ),
    ]
